CREATE TABLE IF NOT EXISTS BOOK (
    id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    title VARCHAR(1000) NOT NULL,
    authors VARCHAR(1000) NOT NULL,
    language_code VARCHAR(20) NOT NULL,
    num_pages VARCHAR(15000) NOT NULL,
    publication_date VARCHAR(400) NOT NULL,
    publisher VARCHAR(400) NOT NULL
);

CREATE TABLE IF NOT EXISTS READER (
    id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    first_name VARCHAR(400) NOT NULL,
    last_name VARCHAR(400) NOT NULL,
    email VARCHAR(400) NOT NULL,
    balance DECIMAL(10,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS BORROWING (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    borrow_date timestamp,
    return_until_date timestamp,
    book_id BIGINT NOT NULL,
    reader_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS FINANCIAL_TRANSACTION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10,2) DEFAULT 0,
    created timestamp,
    description VARCHAR(400),
    reader_id BIGINT NOT NULL
);


ALTER TABLE BORROWING ADD CONSTRAINT borrowing_reader_id FOREIGN KEY (reader_id) REFERENCES reader(id);
ALTER TABLE BORROWING ADD CONSTRAINT borrowing_book_id FOREIGN KEY (book_id) REFERENCES book(id);
ALTER TABLE FINANCIAL_TRANSACTION ADD CONSTRAINT financial_transaction_reader_id FOREIGN KEY (reader_id) REFERENCES reader(id);