CREATE TABLE BOOK (
    book_id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    title VARCHAR(1000) NOT NULL,
    authors VARCHAR(1000) NOT NULL,
    language_code VARCHAR(20) NOT NULL,
    num_pages VARCHAR(15000) NOT NULL,
    publication_date VARCHAR(400) NOT NULL,
    publisher VARCHAR(400) NOT NULL
);

CREATE TABLE READER (
    reader_id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    firstName VARCHAR(400) NOT NULL,
    lastName VARCHAR(400) NOT NULL,
    email VARCHAR(400) NOT NULL
);

CREATE TABLE RENTAL (
    rental_id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    book_id INT CONSTRAINT FK_BOOK REFERENCES BOOK(book_id),
    reader_id INT CONSTRAINT FK_READER REFERENCES READER(reader_id),
    rental_date DATE,
    return_date DATE
);